CREATE DATABASE PopulateDb

BEGIN TRAN
ROLLBACK

DROP TABLE Users
DROP TABLE Addresses
DROP TABLE Geo


CREATE TABLE Users (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Username VARCHAR(50) NULL,
	Phone VARCHAR(50) NULL,
	Website VARCHAR(50) NULL,
	Email VARCHAR(50) NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id)
);

CREATE TABLE Addresses (
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Street VARCHAR(100) NULL,
	Suite VARCHAR(50) NULL,
	City VARCHAR(50) NULL,
	Zipcode VARCHAR(50) NULL,
	GeoId INT FOREIGN KEY REFERENCES Geo(Id)
);

CREATE TABLE Geo (
	Id INT PRIMARY KEY IDENTITY,
	Latitude VARCHAR(50),
	Longitude VARCHAR(50)
);


SELECT * FROM Users
SELECT * FROM Addresses
SELECT * FROM Geo

